version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config-local.properties
      - INDEXING_ENABLED=true
    image: niemen/conductor-server:7.1.3
    networks:
      - internal
    ports:
      - 8080:8080
      - 8090:8090
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - elasticsearch:es
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
  
  redis:
    image: redis:6.2-alpine
    restart: always
    networks:
      - internal
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes: 
      - redis:/data

  elasticsearch:
    image: elasticsearch:7.17.8
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  schellar:
    profiles: ["scheduler"]
    image: flaviostutz/schellar
    environment:
      - CONDUCTOR_API_URL=http://conductor-server:8080/api
      - MONGO_ADDRESS=mongo
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
      - LOG_LEVEL=info
    networks:
      - internal
    ports:
      - 3001:3000
    depends_on:
      - "conductor-server"
    logging:
      driver: "json-file"
      options:
        max-size: "20MB"
        max-file: "5"

  mongo:
    image: mongo:4.1.10
    profiles: ["scheduler"]
    networks:
      - internal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017-27019:27017-27019

volumes:
  esdata-conductor:
    driver: local
  redis:
    driver: local

networks:
  internal: