sources:
  - name: Conductor
    handler:
      openapi:
        source: ${API_URL}
        baseUrl: ${BASE_API_URL}
additionalTypeDefs:
  - ./src/features/workflow/schema.graphql
  - ./src/features/task/schema.graphql
  - ./src/features/workflowHistory/schema.graphql
  - ./src/features/execution/schema.graphql
  - ./src/features/logs/schema.graphql
  - ./src/features/eventHandler/schema.graphql

additionalResolvers:
  - ./src/startup/additionalResolvers.js
serve:
  port: 5000
  cors:
    allowedHeaders: ["authorization", "content-type", "OPTIONS"]
